name: Build using MSYS2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { msystem: MINGW64, pkg_prefix: mingw-w64-x86_64 }
          - { msystem: UCRT64,  pkg_prefix: mingw-w64-ucrt-x86_64 }
          - { msystem: CLANG64, pkg_prefix: mingw-w64-clang-x86_64 }

    runs-on: windows-latest
    name: "${{ github.workflow }}"

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: >-
          base-devel
          make
          git
          ${{ matrix.pkg_prefix }}-cmake
          ${{ matrix.pkg_prefix }}-toolchain
          ${{ matrix.pkg_prefix }}-glm

    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake -B "${{github.workspace}}/build" -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel 4
